const http = require('http');


const server = http.createServer((req,res) => {
    console.log("log generated by index filef from node app"); 
    res.write("Welcome to Node app -- mdified");
    res.end();
});

server.listen(3000);


/*

Enviornmnet + resources
------------------------
OS (linux)
NodeJS (software / CLI)
open Port (3000)
index.js
package.json

Command terminal
-----------------
node index.js

*/